name: error404project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  curved_navigation_bar: ^1.0.1
  image_picker: ^0.8.6+7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  assets:
    - lib/img/avt1.jpg
    - lib/img/todo.jpg
    - lib/img/click.png

  uses-material-design: true

